pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'bilel06/last-one'
        DOCKER_CREDENTIALS_ID = 'dockerhub-creds'
        KUBECONFIG = 'C:\\Users\\21628\\.kube\\config'  // Set the Kubeconfig path here
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Bilel-lefi/-test-123.git'
            }
        }

        stage('Pull Docker Image') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}:latest").pull()
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Deploy the Docker image to Kubernetes using the correct kubeconfig path
                    bat 'kubectl set image deployment/last-one last-one=${DOCKER_IMAGE}:latest --kubeconfig ${KUBECONFIG}'
                }
            }
        }
    }
}
