pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'bilel06/last-one'
        DOCKER_CREDENTIALS_ID = 'dockerhub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Bilel-lefi/-test-123.git'
            }
        }

        stage('Pull Docker Image') {
            steps {
                script {
                    // Récupérer l'image Docker existante
                    docker.image("${DOCKER_IMAGE}:latest").pull()
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }

        stage('Update redeploy-timestamp') {
            steps {
                powershell '''
                    # Obtenir le timestamp actuel au format yyyy-MM-ddTHH:mm:ss
                    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
                    Write-Host "Timestamp: $timestamp"  # Afficher le timestamp pour débogage

                    # Lire et afficher le contenu avant la mise à jour
                    Write-Host "Before update:"
                    Get-Content manifest/deployment.yaml

                    # Mettre à jour redeploy-timestamp avec la valeur du timestamp
                    (Get-Content manifest/deployment.yaml) -replace 'redeploy-timestamp: ".*"', "redeploy-timestamp: `"$timestamp`"" | Set-Content manifest/deployment.yaml

                    # Lire et afficher le contenu après la mise à jour
                    Write-Host "After update:"
                    Get-Content manifest/deployment.yaml
                '''
            }
        }
    }
}
