apiVersion: apps/v1
kind: Deployment
metadata:
  name: last-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: last-one
  template:
    metadata:
      labels:
        app: last-one
      annotations:
        redeploy-timestamp: "1970-01-01T00:00:00" # Valeur initiale, modifiée automatiquement par Jenkins
    spec:
      containers:
        - name: last-one
          image: bilel06/last-one:latest
          ports:
            - containerPort: 80
