apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: last-one
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bilel-lefi/-test-123.git
    targetRevision: master
    path: argocd/manifests 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
